### ISSUE TITLE
Header deb package is contains x86_64 binary, can not build any driver.

### ISSUE THREAD

**Issue by hisaha** [TinkerBoard2/kernel#10]
The header deb package maybe broken.

On the below release page,
https://github.com/TinkerBoard2/kernel/releases/tag/tinker_board_2-debian_10-2.0.0
the linux-headers-4.4.194_4.4.194-1_arm64.deb is distibuted, and the direct link is the below.
https://github.com/TinkerBoard2/kernel/releases/download/tinker_board_2-debian_10-2.0.0/linux-headers-4.4.194_4.4.194-1_arm64.deb

But the binaries in the scripts directory of the deb package is for x86_64,
then I can not build any kernel module for Tinker board2S.

I confirmed it with below steps.

1. wget https://github.com/TinkerBoard2/kernel/releases/download/tinker_board_2-debian_10-2.0.0/linux-headers-4.4.194_4.4.194-1_arm64.deb
2. sudo dpkg -i linux-headers-4.4.194_4.4.194-1_arm64.deb
3. file /usr/src/linux-headers-4.4.194/scripts/recordmcount

At the step 3, file command shows the below output.
/usr/src/linux-headers-4.4.194/scripts/recordmcount: ELF 64-bit LSB shared object, x86-64, version 1 (SYSV), dynamically linked, interpreter /lib64/ld-linux-x86-64.so.2, for GNU/Linux 3.2.0, BuildID[sha1]=10512f7c111d0bd7761d9c8e44dcd64a7e082bfd, not stripped

I think the kernel header package was built on x84_64 machine...
Anyone success to build some driver for the tinker board 2S ?

**Comment by asusiot** [comment]
hello @hisaha, 
please use the file below and try if it fixes the issue: 
https://www.asuswebstorage.com/navigate/a/#/s/54DAD42665A143AD8CF962844578FAF34

**Comment by hisaha** [comment]
Thank you so much. I have tried it but not work.
The below is the error message.

make[1]: Entering directory '/usr/src/linux-headers-4.4.194'
make[1]: *** No rule to make target 'prepare0', needed by 'vdso_prepare'.  Stop.
make[1]: Leaving directory '/usr/src/linux-headers-4.4.194'
make: *** [Makefile:19: px4_drv.ko] Error 2
/var/lib/dkms/px4_drv/0.2.1/build/make.log (END)

After my last post, I continue to try build header packages with various way.
When I build the header package on Tinker board 2S, the error has gone.
I can build and install a driver with target built header package.
But the driver not work properly.

Finally, I gave up to use Tinkerboard 2S with Debian.
I am waiting the recover Tinkerbaord S stock...

**Comment by asusiot** [comment]
hello @hisaha 
may i know what are you trying to build? it'll help us to troubleshoot.
are you trying to build this? 
build px4_drv: https://github.com/nns779/px4_drv

**Comment by hisaha** [comment]
Hi @asusiot 

Yes, I am trying to build px4_drv: https://github.com/nns779/px4_drv as you mentioned.

I could build that driver with the header package with below instruction.
( must be on Tinkerboard 2S with Deian10, root is required. )

**apt-get -y install time zip unzip make gcc python bc git-core device-tree-compiler mtools parted libssl-dev dpkg-dev
git clone https://github.com/TinkerBoard2/kernel.git -b linux4.4-rk3399-debian10 --depth 1
rm -rf ./kernel/.git
cd kernel
make LOCALVERSION= tinker2_defconfig -j16
time make "KCFLAGS=-Wno-restrict -Wno-array-bounds -Wno-zero-length-bounds -Wno-sizeof-pointer-memaccess -Wno-bool-operation" LOCALVERSION= deb-pkg -j16 2>&1 | tee build.log
dpkg -i ../linux-headers-4.4.194_4.4.194-2_arm64.deb**

It takes 2 or 3 hours.

Then, I could build the driver with dkms command.

But when I use the device from multi process (more than 3 ) simultaneously, the process fail to read data from devices.
(Only 2 process success to read data.)

As a next step, I am trying to build and upgrade kernel by built on Tinkerboard 2S itself,
but the kernel installation is failed, because the boot partition is too small.

If you give some comment and advice, it really help me.

**Comment by asusiot** [comment]
hello @hisaha, 

please try update kernel with commands below: 

sudo dd if=boot.img of=/dev/mmcblk0p4 status=progress && sync
sudo reboot

in terms of process failed, we will have to look into it

**Comment by hisaha** [comment]
Thak you so much, @asusiot.

But sorry, I don't understand how to create boot.img from kernel source.

I have read similar tips on uboot thread. 
https://tinker-board.asus.com/forum/index.php?/topic/14989-u-boot-build-error-tinkerboard-2s/

I am primer about uboot system...
I don't understand the relationship between kernel source and uboot source...

**Comment by asusiot** [comment]
hello @hisaha, 

you can use the following:
make ARCH=arm64 tinker2_defconfig
make ARCH=arm64 rk3399-tinker_board_2.img -j4

**Comment by hisaha** [comment]
Hi @asusiot ,

Thank you so much, I can build and install the kernel image with your command like below,
**make "KCFLAGS=-Wno-restrict -Wno-array-bounds -Wno-zero-length-bounds -Wno-sizeof-pointer-memaccess -Wno-bool-operation" LOCALVERSION= rk3399-tinker_board_2.img**

But the driver build is failed with the same error...

I noitced the message that "make[2]: 'include/generated/vdso-offsets.h' is up to date.
  Building modules, stage 2." in the build log of kernel image.

I have seen the similar log "make[1]: *** No rule to make target 'prepare0', needed by 'vdso_prepare'. " at building the px4 driver.

Do you feel some relationship between both log?

**Comment by asusiot** [comment]
hello @hisaha, 

we've reuploaded the header, please have a try: 
https://www.asuswebstorage.com/navigate/a/#/s/9340057B55AF42A398FCE935A06D9BEE4

and this patch can be applied to avoid kernel bug/ build error: 
https://www.asuswebstorage.com/navigate/a/#/s/E858438AFC1B48FC9DAC38D4D46D5FD44

**Comment by hisaha** [comment]
Hi @asusiot,

 I have tried building the driver with your new header package and patch.
The build is succeed, but could not load it.

**sudo modprobe px4_drv
modprobe: ERROR: could not insert 'px4_drv': Exec format error**

I have built the driver with "make ARCH=arm64" option,
I think the Exec format is the same as the 2S...

I need more investigation, but here is my quick trial result.

**Comment by asusiot** [comment]
hello @hisaha , 
please install this header file and rebuild px4_drv. it shall solve the problem: https://www.asuswebstorage.com/navigate/a/#/s/0A9F7E9E14AA4073B98E87C27B4BC0E84

**Comment by hisaha** [comment]
Hi @asusiot,

Thank you so much for providing your new kernel header.
I can build the driver with new header package.
When I get the error of "Exec format error", it seems to be derived from vermagic problem.
(I found the "-dirty" string by modinfo command for px4_drv).

After success to build and install kernel, I get the below error and I can't load the driver...
This is the result of "tail -f /var/log/syslog", when I plugged the target device to USB connector on tinker boad 2S.

Dec 13 00:37:44 linaro-alip kernel: [ 1336.278698] usb 5-1.2: USB disconnect, device number 124
Dec 13 00:37:44 linaro-alip kernel: [ 1336.284097] usb 5-1.2.1: USB disconnect, device number 125
Dec 13 00:37:44 linaro-alip kernel: [ 1336.294105] usb 5-1.2.2: USB disconnect, device number 126
Dec 13 00:37:44 linaro-alip kernel: [ 1336.514664] usb 5-1.2: new high-speed USB device number 127 using xhci-hcd
Dec 13 00:37:44 linaro-alip kernel: [ 1336.623839] usb 5-1.2: New USB device found, idVendor=05e3, idProduct=0608
Dec 13 00:37:44 linaro-alip kernel: [ 1336.630845] usb 5-1.2: New USB device strings: Mfr=0, Product=1, SerialNumber=0
Dec 13 00:37:44 linaro-alip kernel: [ 1336.638386] usb 5-1.2: Product: USB2.0 Hub
Dec 13 00:37:44 linaro-alip kernel: [ 1336.661952] hub 5-1.2:1.0: USB hub found
Dec 13 00:37:44 linaro-alip kernel: [ 1336.666859] hub 5-1.2:1.0: 4 ports detected
**Dec 13 00:37:44 linaro-alip systemd-udevd[2560]: could not open builtin file '/lib/modules/4.4.194/modules.builtin.bin'**
Dec 13 00:37:45 linaro-alip kernel: [ 1336.938528] usb 5-1.2.1: new high-speed USB device number 3 using xhci-hcd
Dec 13 00:37:45 linaro-alip kernel: [ 1337.024275] usb 5-1.2.1: New USB device found, idVendor=0511, idProduct=084a
Dec 13 00:37:45 linaro-alip kernel: [ 1337.031406] usb 5-1.2.1: New USB device strings: Mfr=1, Product=2, SerialNumber=3
Dec 13 00:37:45 linaro-alip kernel: [ 1337.039096] usb 5-1.2.1: Product: PXQ3U4
Dec 13 00:37:45 linaro-alip kernel: [ 1337.043213] usb 5-1.2.1: Manufacturer: PLEX̀
Dec 13 00:37:45 linaro-alip kernel: [ 1337.047702] usb 5-1.2.1: SerialNumber: 000012050003731
Dec 13 00:37:45 linaro-alip kernel: [ 1337.060186] px4_usb 5-1.2.1:1.0: Multi-device power control: enabled
**Dec 13 00:37:45 linaro-alip kernel: [ 1337.066641] px4_usb 5-1.2.1:1.0: px4_device_init: px4_parse_serial_number() failed. (ret: -22)**
Dec 13 00:37:45 linaro-alip kernel: [ 1337.078332] px4_usb: probe of 5-1.2.1:1.0 failed with error -22
**Dec 13 00:37:45 linaro-alip systemd-udevd[2564]: failed to execute '/lib/udev/mtp-probe' 'mtp-probe** **/sys/devices/platform/usb1/fe900000.dwc3/xhci-hcd.11.auto/usb5/5-1/5-1.2/5-1.2.1 5 3': No such file or directory**

I can't judge the error about modules.builtin.bin is problem or not...
Additionally, mtp-probe, xhci-hcd.11.auto may give some hint for me...

Any suggestion really helps me. Thanks.

**Comment by hisaha** [comment]
Hi @asusiot,

Sorry for my last comment.
Finally, I have investigated the last error is derived from the px4 driver source.

After modifying the source version of px4 driver,
the device work perfectly with your last kernel header.

Thank you so much!!
