### ISSUE TITLE
How to use 1-wire on pin#7

### ISSUE THREAD

**Issue by fu054539** [TinkerBoard2/kernel#11]
HI,

I want to use Pin #7(GPIOB0) as 1-wire like a RaspberryPi.
Drivers(wire,w1-gpio,w1-therm) are loaded.
But, Pin #7 does not appear to be working correctly.

I made a "w1-gpio.dtbo" overlay file, and merge into the kernel,but it seems to doesn't work too.

w1-gpio.dts is
-----
/dts-v1/;
/plugin/;

/ {
    compatible = "rockchip,rk3399-tinker_board_2", "rockchip,rk3399";
    fragment@0 {
        target-path = "/";
        __overlay__ {
            w1: onewire@0 {
                gpio-controller;
                #gpio-cells = <0x2>;

                compatible = "w1-gpio";
                pinctrl-names = "default";
                pinctrl-0 = <&w1_pins>;
                gpios = <&gpio0 8 0>;
                status = "okay";
            };
        };
    };

    fragment@1 {
        target = <&gpio0>;
        gpio-controller;
        #gpio-cells = <0x2>;

        __overlay__ {
            w1_pins: w1_pins@0 {
                rockchip,pins = <0 8 3 &pcfg_pull_none>;
                //linux,open-drain;
            };
        };
    };
};

Does anyone have an idea?
Thanks,

**Comment by yishinhung** [comment]
Hi @fu054539 :
     Which version image do you use? The CONFIG_W1 didn't enable in release image.
You need to enable CONFIG_W1 and build the kernel image.
Thank a lot!

**Comment by fu054539** [comment]
Hi @yishinhung :
I download https://github.com/TinkerBoard2/kernel/linux4.4-rk3399-debian10, and build with enable CONFIG_W1.
But, writing 'boot.img' to /dev/sdX4, it doesn't boot.
I don't understand why?

**Comment by yishinhung** [comment]
Hi @fu054539 
    How did you build the image and write image to tinker board 2? 
Maybe you can reference the following link or you can record the uart log.

https://github.com/TinkerBoard/TinkerBoard/wiki/Developer-Guide#kernel-44

Thank a lot!

**Comment by fu054539** [comment]
Hi @yishinhung 
I built image according to the procedure you taught me.
And I wrote the boot.img to Tinker2 with the Ubuntu command line link this:
$ sudo dd if=boot.img of=/dev/sdX4 bs=512 && sync
(X is Tinker Board's device name)

Then, unmount Tinker 2 and standalone boot, u-boot stops when it loads the kernel.
Is it reproduce?

**Comment by fu054539** [comment]
Sorry @yishinhung 
I could build the kernel(1-wire enabled), and burn it, confirmed to boot correctly.
but, 1-wire doesn't seem to work correlctly.

I connect a DS18B20 to pin #7, it doesn't recognize.
In addition, dmesg will display the following message.

root@linaro-alip:~# dmesg | grep w1
[    3.827658] rockchip-pinctrl pinctrl: unable to find group for node w1_pins

w1-gpio.dtbo is referred from:
https://tinker-board.asus.com/forum/index.php?/topic/14898-no-wireguard-headers/&tab=comments#comment-15436

Is there anything wrong with it?

**Comment by yishinhung** [comment]
Hi @fu054539:
    By the following link. You need to enable w1_gpio and w1_therm driver for the DS18B20 devices.
The 7 pin have been config by testclk. You can remove it by item2 and let the pin can be config normal by w1.
I didn't have the DS18B20 and 1 wire devices. Maybe the following information can help you.
Thank a lot!

https://www.waveshare.com/wiki/Raspberry_Pi_Tutorial_Series:_1-Wire_DS18B20_Sensor#:~:text=DS18B20%20is%20a%20common%20temperature,and%20with%20the%20Raspbian%20OS.

1.  arch/arm64/configs/tinker2_defconfig about w1_gpio and w1_therm
+CONFIG_W1=y
+CONFIG_W1_SLAVE_THERM=y
+CONFIG_W1_MASTER_GPIO=y

2. Remove the pin 7 default config: Reference the attachment file remove_teskclk.txt
[remove_teskclk.txt](https://github.com/TinkerBoard2/kernel/files/8938836/remove_teskclk.txt)

**Comment by fu054539** [comment]
Hi @yishinhung 
CONFIGs are set to [*], and I patched to dts your proposed.
A new kernel built and burned and reboot, but dmesg still says:
[    3.814305] Driver for 1-wire Dallas network protocol.
[    3.819605] rockchip-pinctrl pinctrl: unable to find group for node w1_pins

DS18B20 devices are doesn't display at /sys/bus/w1/devices.

I think w1-gpio.dtbo doesn't apply correctly.
I confirmed loading the dtbo is suceeded(U-Boot says load it).

Why is wrong?

**Comment by yishinhung** [comment]
Hi @fu054539 
    Maybe you can modify the following fragment@1 or modify the overlay codes to rk3399-tinker_board_2.dts.
Please try it. Thank a lot!

fragment@1 {
    target = <&pinctrl>;
    __overlay__ {
	w1pins {
            w1_pins: w1_pins@0 {
                rockchip,pins = <0 8 3 &pcfg_pull_none>;
                //linux,open-drain;
            };
	};
    };
};

**Comment by fu054539** [comment]
Hi @yishinhung 

I asked the same questions at https://tinker-board.asus.com/forum/index.php?/topic/15051-how-to-use-1-wire-on-tinker2s/
You answered "You need to modify the /boot/config.txt by the following to enable test_clkout2".

I've confused.
What is the right settings at test_clkout2?

**Comment by yishinhung** [comment]
Hi @fu054539:
    Please ignore the "You need to modify the /boot/config.txt by the following to enable test_clkout2".
I didn't have the 1-wire device so i consider you need to config the pin 7 to test_clkout2 functions at first.
But, by your 1-wire dtbo file, i consider you only need the gpio functions.
Did you work about 1-wire functions?

Thank a lot!

**Comment by fu054539** [comment]
Hi @yishinhung 

Let's get a little information straight.
First, the "test_clk2out" should set off at /boot/config.txt like this:
```
intf:test_clkout2=off
#overlay=w1-gpio    # no use, commented
```
Second, I've changed your proposed dts modifying, such as
```
/ {
	model = "ASUS Tinker Board 2/2S";
	compatible = "rockchip,rk3399-tinker_board_2", "rockchip,rk3399";
	:
	(SNIPPED)
	:
	w1 {
		compatible = "w1-gpio";
		pinctrl-names = "default";
		pinctrl-0 = <&w1_gpio_pins>;
		gpios = <&gpio0 8 GPIO_ACTIVE_HIGH>;
	};
};

&pinctrl {
        pinctrl-names = "default";
        pinctrl-0 = <&gpio_init>;
	:
	(SNIPPED)
	:
	onewire {
		w1_gpio_pins: w1-gpio-pins {
			rockchip,pins = <0 8 3 &pcfg_pull_none>;
		};
	};
};
```

In this case, gpio readall says:
```
+-----+-----+---------+------+---+--Tinker--+---+------+---------+-----+-----+
 | CPU | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | CPU |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 |     |     |    3.3v |      |   |  1 || 2  |   |      | 5v      |     |     |
 |  73 |   8 | GPIO2B1 |   IN | 1 |  3 || 4  |   |      | 5v      |     |     |
 |  74 |   9 | GPIO2B2 |   IN | 0 |  5 || 6  |   |      | 0v      |     |     |
 |   8 |   7 | GPIO0B0 |   IN | 0 |  7 || 8  | 1 | IN   | GPIO2C1 | 15  | 81  |
 |     |     |      0v |      |   |  9 || 10 | 1 | IN   | GPIO2C0 | 16  | 80  |
 |  83 |   0 | GPIO2C3 |   IN | 1 | 11 || 12 | 0 | IN   | GPIO3D0 | 1   | 120 |
 |  85 |   2 | GPIO2C5 |   IN | 0 | 13 || 14 |   |      | 0v      |     |     |
 |  84 |   3 | GPIO2C4 |   IN | 0 | 15 || 16 | 0 | IN   | GPIO2C6 | 4   | 86  |
 |     |     |    3.3v |      |   | 17 || 18 | 0 | IN   | GPIO2C7 | 5   | 87  |
 |  40 |  12 | GPIO1B0 |   IN | 1 | 19 || 20 |   |      | 0v      |     |     |
 |  39 |  13 | GPIO1A7 |   IN | 1 | 21 || 22 | 0 | IN   | GPIO3D4 | 6   | 124 |
 |  41 |  14 | GPIO1B1 |   IN | 1 | 23 || 24 | 1 | IN   | GPIO1B2 | 10  | 42  |
 |     |     |      0v |      |   | 25 || 26 | 0 | IN   | GPIO0A6 | 11  | 6   |
 |  71 |  30 | GPIO2A7 |   IN | 1 | 27 || 28 | 1 | IN   | GPIO2B0 | 31  | 72  |
 | 126 |  21 | GPIO3D6 |   IN | 0 | 29 || 30 |   |      | 0v      |     |     |
 | 125 |  22 | GPIO3D5 |   IN | 0 | 31 || 32 | 0 | IN   | GPIO4C2 | 26  | 146 |
 | 150 |  23 | GPIO4C6 |  OUT | 1 | 33 || 34 |   |      | 0v      |     |     |
 | 121 |  24 | GPIO3D1 |   IN | 0 | 35 || 36 | 1 | IN   | GPIO2C2 | 27  | 82  |
 | 149 |  25 | GPIO4C5 |   IN | 0 | 37 || 38 | 0 | IN   | GPIO3D3 | 28  | 123 |
 |     |     |      0v |      |   | 39 || 40 | 0 | IN   | GPIO3D7 | 29  | 127 |
 +-----+-----+---------+------+---+----++----+---+------+---------+-----+-----+
 | CPU | wPi |   Name  | Mode | V | Physical | V | Mode | Name    | wPi | CPU |
 +-----+-----+---------+------+---+--Tinker--+---+------+---------+-----+-----+
```

and "cat /sys/kernel/debug/gpio" says:
```
GPIOs 0-31, platform/pinctrl, gpio0:
 gpio-3   (                    |?                   ) out lo
 gpio-4   (                    |?                   ) out hi
 gpio-5   (                    |GPIO Key Power      ) in  hi
 gpio-8   (                    |w1                  ) in  lo
 gpio-10  (                    |?                   ) out lo
 gpio-12  (                    |ep                  ) out hi

GPIOs 32-63, platform/pinctrl, gpio1:
 gpio-34  (                    |int-n               ) in  hi
 gpio-35  (                    |vbus-5v             ) out lo
 gpio-38  (                    |PMIC_RESET          ) out lo
 gpio-46  (                    |vsel                ) out lo
 gpio-49  (                    |vsel                ) out lo

GPIOs 64-95, platform/pinctrl, gpio2:
 gpio-76  (                    |hub-vbus            ) out hi
 gpio-90  (                    |bt_default_wake     ) in  lo

GPIOs 96-127, platform/pinctrl, gpio3:
 gpio-111 (                    |mdio-reset          ) out hi
 gpio-112 (                    |gmac_wol_io         ) in  lo

GPIOs 128-159, platform/pinctrl, gpio4:
 gpio-158 (                    |vcc_lcd             ) out lo
```

after reboot, "dmesg | grep w1" says:
```
# dmesg | grep w1
[    3.822923] of_get_named_gpiod_flags: parsed 'gpios' property of node '/w1[0]' - status (0)
[    3.822953] of_get_named_gpiod_flags: can't parse 'gpios' property of node '/w1[1]'
[    5.103116] w1_master_driver w1_bus_master1: w1_search: max_slave_count 64 reached, will continue next search.
[    8.297548] wire: exports duplicate symbol w1_add_master_device (owned by kernel)
```

I think w1 gpio is set properly, but DS18B20 devices doesn't recognize.
What more do I need to know?
Thanks,

**Comment by yishinhung** [comment]
Hi @fu054539
    Maybe you can change the test pin from pin 7 to pin 5?
I think the  driver have work by w1 dts config. 

- pin 5
gpios = <&gpio2 10 GPIO_ACTIVE_HIGH>;

**Comment by fu054539** [comment]
Hi @yishinhung 
Sorry, I can't connect it to pin 5.
Because it's already used for another purpose.

Possibly, I think that the reason why it is not working well is as follows.
```
# dmesg | gewp w1
[    3.822953] of_get_named_gpiod_flags: can't parse 'gpios' property of node '/w1[1]'
```

Is there a way to solve this?

**Comment by yishinhung** [comment]
Hi @fu054539 
     Maybe you can try pin 11 for w1-gpio at first. 
The following error message mean it's need another gpio pin define in dts. But, i think the DS18B20 just need one gpio pin.

# dmesg | gewp w1
[    3.822953] of_get_named_gpiod_flags: can't parse 'gpios' property of node '/w1[1]'

**Comment by fu054539** [comment]
Hi @yishinhung 

I think your point is justified.
However, I just want to use pin 7, and I don't want to use other GPIO pins.

This is because other Tinker series (Tinker S R2.0, etc.) can use pin 7 as 1-wire.

**Comment by yishinhung** [comment]
Hi @fu054539 
     Maybe you can try it to verify whether the 7 pin problem because the Tinker 2 is RK3399 chip
Thank a lot!

**Comment by fu054539** [comment]
Hi @yishinhung 

How to test pin7 is responding correctly?

**Comment by yishinhung** [comment]
Hi @fu054539:
       The pin 7 have hardware limitation on Tinker Board 2(RK3399). Please use the other pin for the 1 wire functions
Thank a lot!

**Comment by fu054539** [comment]
Hi @yishinhung 

OK, I understand.
Thank you for your support.
